assignment2/social_network/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('hello');
});


Route::resource('post', 'PostController');
Route::resource('comment','CommentController');
Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));
Route::post('user/search', array('as' => 'user.search', 'uses' => 'UserController@search'));
Route::get('docs', function()
{
  return View::make('sn.docs');
});
Route::resource('user', 'UserController');
Route::get('/', array('as'=>'home', 'uses'=> 'PostController@index'));


// Put this in the model
function ageCalculator($dob){
		if(!empty($dob)){
			$birthdate = new DateTime($dob);
			$today   = new DateTime('today');
			$age = $birthdate->diff($today)->y;
			return $age;
		}else{
			return 0;
		}
}

assignment2/social_network/app/views/sn/add_comment.blade.php
@extends('layouts.master') 
@section('title')
Add Comment
@stop
@section('content')
        <div class="col-xs-12" style="padding:10px;">
            <table class="table table-hover">
                <tbody class="col-xs-12">
                    <tr><th class="col-xs-1">{{ HTML::image('images/technics.jpg', 'technics', array( 'width' => 84, 'height' => 84 )) }}</th><td></td></tr>
                    <tr><th class="col-xs-1">Author: </th><td>{{{ $post->posts_author }}}</td></tr>
                    <tr><th class="col-xs-1">Title: </th><td>{{{ $post->posts_title }}}</td></tr>
                    <tr><th class="col-xs-1">Message: </th><td>{{{ $post->posts_message }}}</td></tr>
                </tbody>
            </table>
            <hr>
            <h3 style="padding:10px;">Comment on Post</h3>
            <form class="create well" method="post" action="{{ url ("comment_action/$post->id") }}">
                <div class="form-group">
                    <label>Author: </label>
                    <input type="text" class="createtext col-xs-5" name="author">
                </div>
                <div class="form-group">
                    <label>Message: </label>
                    <textarea class="form-control" rows="4" name="message"></textarea>
                </div>
                <button type="submit" class="createsub btn btn-info">Add Comment</button>
            </form> 
            <h3 style="padding:10px;">Comments</h3>
            @if($comments)
            @foreach($comments as $comment) 
            <table class="table table-hover">
                <tbody class="col-xs-12">
                    <tr><th class="col-xs-1">Author: </th><td>{{{ $comment->comments_author }}}</td></tr>
                    <tr><th class="col-xs-1">Message: </th><td>{{{ $comment->comments_message }}}</td></tr>
                    <tr><th class="col-xs-1"><a href="{{{ url("delete_comment/$comment->id/$comment->postsid") }}}">Delete</a></th><td></td></tr>
                </tbody>
            </table>
            @endforeach
            @else
            <p>No comments yet.</p>
            @endif
</div>
@stop

assignment2/social_network/app/views/sn/comments.blade.php
@extends('layouts.master') 
@section('title')
Add Comment
@stop
@section('content')

        <div class="col-xs-12" style="padding:10px;">
            <table class="table table-hover">
                <tbody class="col-xs-12">
                    <tr><th class="col-xs-1">{{ HTML::image($post->image, 'profile picture') }}</th><td></td></tr>
                    <tr><th class="col-xs-1">Email: </th><td>{{{ $post->email }}}</td></tr>
                    <tr><th class="col-xs-1">Title: </th><td>{{{ $post->title }}}</td></tr>
                    <tr><th class="col-xs-1">Message: </th><td>{{{ $post->message }}}</td></tr>
                </tbody>
            </table>
            <hr>
            @if(Auth::check())
            <h3 style="padding:10px;">Comment on Post</h3>
            {{Form::open(array('method'=>'POST','route'=> array('comment.store',$post->id), 'class' => 'create well', 'style' => 'margin:0px 10px'))}}
                <div class="form-group">
                    {{ Form::hidden('id', $post->id) }}
                    {{ Form::label('message', 'Message:', array('style' => 'float:left;')) }}
                    {{ Form::textarea('message', null, array('class'=>'form-control', 'rows'=>'4')) }}
                </div>
                    {{ Form::submit('Add Comment', array('class' => 'createsub btn btn-info')) }}
            {{ Form::close() }}
            @endif
            
            <h3 style="padding:10px;">Comments</h3>
            @if(isset($comments))
            @foreach($comments as $comment) 
            <table class="table table-hover">
                <tbody class="col-xs-12">
                    <tr><th>@if($comment->image){{ HTML::image($comment->image, 'profile picture') }}@endif</th><td></td></tr>
                    <tr><th class="col-xs-1">Author: </th><td>@if($comment->f_name && $comment->l_name){{{ $comment->f_name }}} {{{ $comment->l_name }}}@else {{{ $comment->email }}}@endif</td></tr>
                    <tr><th class="col-xs-1">Message: </th><td>{{{ $comment->message }}}</td></tr>
                    
                    <tr><th class="col-xs-1">
                        @if(Auth::check() && Auth::user()->email == $comment->email)
                        {{ Form::open(['method' => 'DELETE', 'route' => ['comment.destroy', $comment->id]]) }}
                        {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                        {{ Form::close() }}</th>@endif<td></td></tr>
                </tbody>
            </table>
            @endforeach
            @else
            <p>No comments yet.</p>
            @endif
            
</div>
@stop

assignment2/social_network/app/views/sn/docs.blade.php
@extends('layouts.master')

@section('title')
Documentation
@stop
@section('content')

<h1>Documentation</h1>

<h4>Entity Relationship Diagram</h4>
{{ HTML::image('images/entity_relationship_diagram.png', 'entity relationship diagram', array( 'width' => 375, 'height' => 200 )) }}

<h4>Website Routes</h4>
{{ HTML::image('images/website_diagram.png', 'website diagram1', array( 'width' => 370, 'height' => 240 )) }}
{{ HTML::image('images/website_diagram2.png', 'website diagram2', array( 'width' => 370, 'height' => 240 )) }}

<ol style="margin:10px">
    <li>I was unable to complete any <b>friends features</b> at this point.</li>
    <li><b>Unable</b> to update profile picture</li>
    <li>Users <b>don't</b> exactly have a profile page</li>
    <li><b>Pagination not completed</b></li>
    <li><b>Approach I took: </b>Work as hard as possible. I beleieve the majority of this assignment was achieved by reading lecture notes and completing each lab</li>
    <li>I spent many hours working on this each day, in the end I just ran out of time.</li>
</ol>
@stop

assignment2/social_network/app/views/sn/edit.blade.php
@extends('layouts.master')
@section('title')
Edit Post
@stop
@section('content')
<h3 style="margin:10px;">Edit Post</h3>
{{ Form::model($post, array('method' => 'PUT', 'class' => 'well', 'route' => array('post.update', $post->id))) }}
    <div class="form-group">
        {{ Form::label('title', 'Title:') }}
        {{ $errors->first('title','<small class=error>:message</small>') }}
        {{ Form::text('title', null, array('class' => 'form-control')) }}
    </div>
    <div class="form-group">
        {{ Form::label('message', 'Message:', array('style' => 'float:left;')) }}
        {{ $errors->first('message','<small class=error>:message</small>') }}
        {{ Form::textarea('message', null, array('class'=>'form-control', 'rows'=>'4')) }}
    </div>
    <div class="form-group">
        {{ Form::select('privacy', array('1' => 'Public', '2' => 'Friends', '3' => 'Private'),'2') }}
    </div>
        {{ Form::submit('Save', array('class' => 'createsub btn btn-info')) }}
		{{ link_to_route('post.index', 'Cancel', $post->id, array('class' => 'btn btn-info')) }}
</form>
{{ Form::close() }}
@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif
@stop

assignment2/social_network/app/views/sn/feed.blade.php
@extends('layouts.master') 
@section('title')
News Feed
@stop
@section('content')
@if (!Auth::check())
 	{{ Form::open(array('route' => 'user.login', 'class' => 'create well'))  }}
 	    {{ Session::get('login_error') }}
	    <div class="form-group">
	        {{ Form::label('email', 'Email') }}
	        {{ Form::email('email', null, array('class' => 'form-control')) }}
	    </div>
	    <div class="form-group">        
	        {{ Form::label('password', 'Password') }}
	        {{ Form::password('password', array('class' => 'form-control')) }}
	    </div>
	        {{ Form::submit('Login', array('class' => 'createsub btn btn-info')) }}
	{{ Form::close() }}
@endif

<!--Form to add a new post-->
<h3 style="margin:10px;"></h3>
@if (Auth::check())
<h3 style="margin:10px;">Create Post</h3>                	
{{ Form::open(array('POST' => 'PostController@store', 'class' => 'create well', 'style' => 'margin:0px 10px')) }}
    <div class="form-group">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('title', null, array('class' => 'form-control')) }}
    </div>
    <div class="form-group">
        {{ Form::label('message', 'Message', array('style' => 'float:left;')) }}
        {{ Form::textarea('message', null, array('class'=>'form-control', 'rows'=>'4')) }}
    </div>
    <div class="form-group">
        {{ Form::select('privacy', array('1' => 'Public', '2' => 'Friends', '3' => 'Private'),'2') }}
    </div>
        {{ Form::submit('Create', array('class' => 'createsub btn btn-info')) }}
{{ Form::close() }}
@endif
@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif
<h3 style="margin:10px;">News Feed</h3>   
                            @if (count($posts))
                            
                            <!--Loop for each Post in Posts Table if user is logged in -->
                         
                            @foreach($posts as $post)
                        
                                @if ((Session::get('privacy') == 'open') && ($post->privacy != 3)) 
                                <table class="table table-hover">
                                    <tbody class="col-xs-12">
                                        <tr><th class="col-xs-1">{{ HTML::image($post->image, 'profile picture') }}</th><td></td></tr>
                                        <tr><th class="col-xs-1">Email: </th><td>{{{ $post->email }}}</td></tr>
                                        <tr><th class="col-xs-1">Title: </th><td>{{{ $post->title }}}</td></tr>
                                        <tr><th class="col-xs-1">Message: </th><td>{{{ $post->message }}}</td></tr>
                                        <tr><td class="col-xs-1">{{ link_to_route('post.show', 'Comments', $post->id, array('class' => 'btn btn-info', 'style' => 'float:left')) }}</td>
                                            <!--If user is authorised and if user email = the posts email field-->
                                            @if ((Auth::check()) && (Auth::user()->email == $post->email))
                                            <td style="width:30em">{{ link_to_route('post.edit', 'Edit', $post->id, array('class' => 'btn btn-info', 'style' => 'float:left')) }}
                                            {{ Form::open(['method' => 'DELETE', 'route' => ['post.destroy', $post->id]]) }}
                                            {{ Form::submit('Delete', ['class' => 'btn btn-danger', 'style' => 'margin-left:1em; float:left']) }}
                                            {{ Form::close() }}</td></tr>
                                            @else<td></td></tr>
                                    </tbody>
                                </table>
                                @endif
                                @if(($post->priavcy == 3) && (Auth::check()) && (Auth::user()->email == $post->email))
                                <table class="table table-hover">
                                    <tbody class="col-xs-12">
                                        <tr><th class="col-xs-1">{{ HTML::image($post->image, 'profile picture') }}</th><td></td></tr>
                                        <tr><th class="col-xs-1">Email: </th><td>{{{ $post->email }}}</td></tr>
                                        <tr><th class="col-xs-1">Title: </th><td>{{{ $post->title }}}</td></tr>
                                        <tr><th class="col-xs-1">Message: </th><td>{{{ $post->message }}}</td></tr>
                                        <tr><td class="col-xs-1">{{ link_to_route('post.show', 'Comments', $post->id, array('class' => 'btn btn-info', 'style' => 'float:left')) }}</td>
                                            <td style="width:30em">{{ link_to_route('post.edit', 'Edit', $post->id, array('class' => 'btn btn-info', 'style' => 'float:left')) }}
                                            {{ Form::open(['method' => 'DELETE', 'route' => ['post.destroy', $post->id]]) }}
                                            {{ Form::submit('Delete', ['class' => 'btn btn-danger', 'style' => 'margin-left:1em; float:left']) }}
                                            {{ Form::close() }}</td></tr>
                                    </tbody>
                                </table> 
                                @endif
                            <!--Loop for each Post in Posts Table if user is not logged in-->
                            @elseif(Session::get('privacy') != 'open')
                            @if ($post->privacy == 1)
                                <table class="table table-hover">
                                    <tbody class="col-xs-12">
                                        <tr><th class="col-xs-1">{{ HTML::image($post->image, 'profile picture') }}</th><td></td></tr>
                                        <tr><th class="col-xs-1">Email: </th><td>{{{ $post->email }}}</td></tr>
                                        <tr><th class="col-xs-1">Title: </th><td>{{{ $post->title }}}</td></tr>
                                        <tr><th class="col-xs-1">Message: </th><td>{{{ $post->message }}}</td></tr>
                                        <tr><td class="col-xs-1">{{ link_to_route('post.show', 'Comments', $post->id, array('class' => 'btn btn-info', 'style' => 'float:left')) }}</td>
                                        <td style="width:30em">
                                            <!--If the user is authorised-->
                                            @if (Auth::check())
                                            {{ link_to_route('post.edit', 'Edit', $post->id, array('class' => 'btn btn-info')) }}
                                            {{ Form::open(['method' => 'DELETE', 'route' => ['post.destroy', $post->id]]) }}
                                            {{ Form::submit('Delete', ['class' => 'btn btn-danger', 'style' => 'margin-left:1em']) }}
                                            {{ Form::close() }}</td></tr>@endif
                                    </tbody>
                                </table>
                            @endif
                            @endif
                            @endforeach
                            @else
                            <p>It's like a ghost town here.</p>
                            @endif
                            
@stop